### ISSUE TITLE
dropDownList selectedText not showing( in Editor )

### ISSUE THREAD

**Issue by imdaddyjnj** [NeoAxis/NeoAxisEngine#14]
All of dropDownLists's selectedText not showing  in Editor
at NeoAxis version( 2020.7, 2020.6).

And I tried to fix problem like this
It's work but a little bit not aligned other ui controls.

(at Sources\Engine\NeoAxis.Core\Editor\HierarchicalContainer\HCItemEnumDropDown.cs)

https://github.com/NeoAxis/NeoAxisEngine/blob/a1e65f17a39d2d8eb4c0538902487c4d0b435e4d/Sources/Engine/NeoAxis.Core/Editor/HierarchicalContainer/HCItemEnumDropDown.cs#L71

```
public override void UpdateControl()
{
    base.UpdateControl();

    bool readOnly = !CanEditValue();
    var control = ( HCGridDropDownButton /*IHCDropDownButton*/)CreatedControlInsidePropertyItemControl;
    control.Button.Enabled = !readOnly;

    //update width. Anchor for this control works bad in .NET Core
    control.Button.Width = control.Width - control.Button.Location.X;

    //[begin] my temporal fix
    if( control.Button.Height < control.Button.PreferredSize.Height )
    {
        control.Button.Height = control.Button.PreferredSize.Height;
    }
    //[end] my temporal fix
    
    ....
}
```

I hope it can help someone...

![img_compare](https://user-images.githubusercontent.com/73229941/96859939-17675100-149d-11eb-9895-debc7cd37202.png)

**Comment by IvanEfimov** [comment]
Please tell what Windows version, font size in Display settings?

**Comment by imdaddyjnj** [comment]
Windows 10 (20H1), Microsoft Sans serif 8pt

**Comment by IvanEfimov** [comment]
Thanks, please check reuploaded build. It is must be fixed, although alignment can still not ideal. Also other small fixes are done.
https://www.neoaxis.com/downloads/NeoAxisEngine-2020.7.1.exe
https://www.neoaxis.com/downloads/NeoAxisEngine-2020.7.1.exe.torrent

**Comment by imdaddyjnj** [comment]
Thanks a lot.
It fixed!

![fixed_1](https://user-images.githubusercontent.com/73229941/96942637-a3669080-1510-11eb-9ee7-c703f89cea11.png)
![fixed_2](https://user-images.githubusercontent.com/73229941/96942641-a6fa1780-1510-11eb-9b7d-00160a76740f.png)


After
(: https://github.com/NeoAxis/NeoAxisEngine/commit/ec1ac30c86f0fa3397835b834a0b21ca6efb2fdc)
